//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tbl
    {
        public int Eno { get; set; }
        public string Ename { get; set; }
        public Nullable<decimal> Salary { get; set; }
    }
}
