//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_WCF_Rest_XML_Format
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int EmpId { get; set; }
        public string EmpName { get; set; }
        public Nullable<double> EmpSalary { get; set; }
    }
}
